{% set name = "neptune-prophet" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/neptune-prophet/archive/{{ version }}.tar.gz
  sha256: 25acfdd945e15243642787a8996c829b9bbc59f2472b2154183df4ded701dd50

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base <=3.4.3
    - neptune-client >=0.15.0
    - numpy
    - pandas
    - prophet >=1.0
    - scipy
    - statsmodels

test:
  imports:
    - neptune_prophet
    - neptune_prophet.impl
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Prophet
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/
  dev_url: https://github.com/neptune-ai/neptune-prophet

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - twolodzko
